import type { I18nKey } from "../i18n/types/i18n-key";
import { FieldKey, type FieldKey as FieldKeyType } from "./field-keys";

export const fieldLabelMap: Record<FieldKeyType, I18nKey> = {
  [FieldKey.ACCOUNT_ID]: "field.account_id.label",
  [FieldKey.ACTIVE]: "field.active.label",
  [FieldKey.AVATAR]: "field.avatar.label",
  [FieldKey.BALANCE]: "field.balance.label",
  [FieldKey.BIRTH_DATE]: "field.birth_date.label",
  [FieldKey.BODY]: "field.body.label",
  [FieldKey.CANONICAL_VALUE]: "field.canonical_value.label",
  [FieldKey.CATEGORY_ID]: "field.category_id.label",
  [FieldKey.COLOR]: "field.color.label",
  [FieldKey.COUNTRY]: "field.country.label",
  [FieldKey.CREDIT_CARD_ID]: "field.credit_card_id.label",
  [FieldKey.CURRENCY]: "field.currency.label",
  [FieldKey.CURRENT_PASSWORD]: "field.current_password.label",
  [FieldKey.DATE]: "field.date.label",
  [FieldKey.DISPLAY_VALUE]: "field.display_value.label",
  [FieldKey.EMAIL]: "field.email.label",
  [FieldKey.CONFIRM_PASSWORD]: "field.confirm_password.label",
  [FieldKey.FIRST_NAME]: "field.first_name.label",
  [FieldKey.FLAG]: "field.flag.label",
  [FieldKey.HIDE_VALUES]: "field.hide_values.label",
  [FieldKey.INSTITUTION]: "field.institution.label",
  [FieldKey.IS_INSTALLMENT]: "field.is_installment.label",
  [FieldKey.IS_RECURRING]: "field.is_recurring.label",
  [FieldKey.LANGUAGE]: "field.language.label",
  [FieldKey.LAST_NAME]: "field.last_name.label",
  [FieldKey.LIMIT]: "field.limit.label",
  [FieldKey.MESSAGE]: "field.message.label",
  [FieldKey.NAME]: "field.name.label",
  [FieldKey.OBSERVATION]: "field.observation.label",
  [FieldKey.PASSWORD]: "field.password.label",
  [FieldKey.PAYMENT_DAY]: "field.payment_day.label",
  [FieldKey.PHONE]: "field.phone.label",
  [FieldKey.PROFILE]: "field.profile.label",
  [FieldKey.SUBCATEGORY_ID]: "field.subcategory_id.label",
  [FieldKey.TAGS]: "field.tags.label",
  [FieldKey.TERMS_ACCEPTED]: "field.terms_accepted.label",
  [FieldKey.THEME]: "field.theme.label",
  [FieldKey.TITLE]: "field.title.label",
  [FieldKey.TOTAL_MONTHS]: "field.total_months.label",
  [FieldKey.TRANSACTION_SOURCE]: "field.transaction_source.label",
  [FieldKey.TRANSACTION_TYPE]: "field.transaction_type.label",
  [FieldKey.TYPE]: "field.type.label",
  [FieldKey.USER_ID]: "field.user_id.label",
  [FieldKey.VALUE]: "field.value.label",
  [FieldKey.IMAGE]: "field.image.label",
  [FieldKey.AUDIO]: "field.audio.label",
  [FieldKey.FILE]: "field.file.label",
};
